<H1>Import required libraries for analysis and visualization 

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import plotly.io as pio


<h1>Load the dataset for this analysis</h1>
<p>This data set contains customers information on 7,043 customers from a Telecommunication company in California in Q2 2022</p>
<p>This analysis will make use of 2 data set

In [57]:
customer_churn= pd.read_csv(r'C:\EXCEL\Telecom+Customer+Churn\telecom_customer_churn.csv')
customer_churn.head()

Customer ID  Gender  Age Married  Number of Dependents          City  \
0  0002-ORFBO  Female   37     Yes                     0  Frazier Park   
1  0003-MKNFE    Male   46      No                     0      Glendale   
2  0004-TLHLJ    Male   50      No                     0    Costa Mesa   
3  0011-IGKFF    Male   78     Yes                     0      Martinez   
4  0013-EXCHZ  Female   75     Yes                     0     Camarillo   

   Zip Code   Latitude   Longitude  Number of Referrals  ...   Payment Method  \
0     93225  34.827662 -118.999073                    2  ...      Credit Card   
1     91206  34.162515 -118.203869                    0  ...      Credit Card   
2     92627  33.645672 -117.922613                    0  ...  Bank Withdrawal   
3     94553  38.014457 -122.115432                    1  ...  Bank Withdrawal   
4     93010  34.227846 -119.079903                    3  ...      Credit Card   

  Monthly Charge Total Charges  Total Refunds Total Extra Data Charges  \
0           65.6        593.30           0.00                        0   
1           -4.0        542.40          38.33                       10   
2           73.9        280.85           0.00                        0   
3           98.0       1237.85           0.00                        0   
4           83.9        267.40           0.00                        0   

  Total Long Distance Charges Total Revenue  Customer Status   Churn Category  \
0                      381.51        974.81           Stayed              NaN   
1                       96.21        610.28           Stayed              NaN   
2                      134.60        415.45          Churned       Competitor   
3                      361.66       1599.51          Churned  Dissatisfaction   
4                       22.14        289.54          Churned  Dissatisfaction   

                    Churn Reason  
0                            NaN  
1                            NaN  
2  Competitor had better devices  
3        Product dissatisfaction  
4            Network reliability  

[5 rows x 38 columns]

In [58]:
zip_code_pop= pd.read_csv(r'C:\EXCEL\Telecom+Customer+Churn\telecom_zipcode_population.csv')
zip_code_pop.head(2)

Zip Code  Population
0     90001       54492
1     90002       44586

<h1>Data wrangling

In [59]:
#identify and count missing data
print(customer_churn.isnull().sum())


Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                   0
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                  

In [60]:
#convert data type
# Firts i will check the data type
customer_churn.dtypes

Customer ID                           object
Gender                                object
Age                                    int64
Married                               object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download              float64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming 

I think the data type is okay for now so i will not change anything yet

<h1>Now i will get into exploratory data analysis</h1>
<p></p>
<h3> We will find out why people leave and also indentify the high value customers</h3>
<h4>Lets find out why poeple leave first</h4>

In [61]:
#slice out the churn rows from the 'customer status' column
churned_customers= customer_churn.loc[customer_churn['Customer Status']=='Churned']
print('This dataframe will contain only the rows with churned customers')
churned_customers.head(2)


This dataframe will contain only the rows with churned customers


Customer ID Gender  Age Married  Number of Dependents        City  Zip Code  \
2  0004-TLHLJ   Male   50      No                     0  Costa Mesa     92627   
3  0011-IGKFF   Male   78     Yes                     0    Martinez     94553   

    Latitude   Longitude  Number of Referrals  ...   Payment Method  \
2  33.645672 -117.922613                    0  ...  Bank Withdrawal   
3  38.014457 -122.115432                    1  ...  Bank Withdrawal   

  Monthly Charge Total Charges  Total Refunds Total Extra Data Charges  \
2           73.9        280.85            0.0                        0   
3           98.0       1237.85            0.0                        0   

  Total Long Distance Charges Total Revenue  Customer Status   Churn Category  \
2                      134.60        415.45          Churned       Competitor   
3                      361.66       1599.51          Churned  Dissatisfaction   

                    Churn Reason  
2  Competitor had better devices  
3        Product dissatisfaction  

[2 rows x 38 columns]

In [62]:
#I will set the churn category as the index for easy analysis and visualization
easy=churned_customers.set_index("Churn Category")
easy.head(2)

Customer ID Gender  Age Married  Number of Dependents  \
Churn Category                                                          
Competitor       0004-TLHLJ   Male   50      No                     0   
Dissatisfaction  0011-IGKFF   Male   78     Yes                     0   

                       City  Zip Code   Latitude   Longitude  \
Churn Category                                                 
Competitor       Costa Mesa     92627  33.645672 -117.922613   
Dissatisfaction    Martinez     94553  38.014457 -122.115432   

                 Number of Referrals  ...  Paperless Billing   Payment Method  \
Churn Category                        ...                                       
Competitor                         0  ...                Yes  Bank Withdrawal   
Dissatisfaction                    1  ...                Yes  Bank Withdrawal   

                Monthly Charge  Total Charges Total Refunds  \
Churn Category                                                
Competitor                73.9         280.85           0.0   
Dissatisfaction           98.0        1237.85           0.0   

                Total Extra Data Charges Total Long Distance Charges  \
Churn Category                                                         
Competitor                             0                      134.60   
Dissatisfaction                        0                      361.66   

                 Total Revenue Customer Status                   Churn Reason  
Churn Category                                                                 
Competitor              415.45         Churned  Competitor had better devices  
Dissatisfaction        1599.51         Churned        Product dissatisfaction  

[2 rows x 37 columns]

In [63]:
easy1=churned_customers['Churn Category'].value_counts().sort_values()
easy1

Other              182
Price              211
Attitude           314
Dissatisfaction    321
Competitor         841
Name: Churn Category, dtype: int64

In [90]:
px.data.gapminder()
for templates in ['plotly_dark']:
 category_fig=px.bar(easy1,color_discrete_sequence=px.colors.sequential.RdBu,
title= 'Categories of churned customers ', template=templates,
labels={'index':'Churn category', 'value':'Count of customers',}

)
category_fig.show()


It is clear that customers leave because of competitors. Now lets find out there reasons for going to the competitors. 

In [65]:
comp=churned_customers['Churn Reason'].value_counts().sort_values(ascending=True)
comp1=comp.tail(10)
comp1

Network reliability                           72
Product dissatisfaction                       77
Price too high                                78
Attitude of service provider                  94
Competitor offered higher download speeds    100
Competitor offered more data                 117
Don't know                                   130
Attitude of support person                   220
Competitor made better offer                 311
Competitor had better devices                313
Name: Churn Reason, dtype: int64

In [66]:
#To visualize the above numbers
px.data.gapminder()
for templates in ['plotly_dark']:
 reason_for_leaving_fig=px.bar(comp1,color_discrete_sequence=px.colors.sequential.RdBu,
title= 'Number of customer that churn and their reasons ',template=templates,
labels={'index':'Churn reason', 'value':'Count of customers'},
orientation='h' )
reason_for_leaving_fig.show()



Seems most people left because <b>competitors had better device and made better offer</b>

<h4> The second largest number of customers left when they got better offer, so lets find out the offers that is given to these customers

In [67]:
offer=churned_customers['Offer'].value_counts().sort_values()

offer

Offer A      35
Offer C      95
Offer B     101
Offer D     161
Offer E     426
None       1051
Name: Offer, dtype: int64

Customers without offers have left mostly but those with offer E and has also a high number of churned customers

In [68]:
#Lets shoe the above in a chart
px.data.gapminder()
for templates in ['plotly_dark']:
 offer_no_fig=px.scatter(offer,color_discrete_sequence=px.colors.sequential.RdBu,
title= 'Offers made to churned customers',template=templates,
labels={'index':'Offers', 'value':'Count of customers'} )
offer_no_fig.show()

In [69]:
churned_customers[churned_customers['Number of Referrals'] > 9 ]


Empty DataFrame
Columns: [Customer ID, Gender, Age, Married, Number of Dependents, City, Zip Code, Latitude, Longitude, Number of Referrals, Tenure in Months, Offer, Phone Service, Avg Monthly Long Distance Charges, Multiple Lines, Internet Service, Internet Type, Avg Monthly GB Download, Online Security, Online Backup, Device Protection Plan, Premium Tech Support, Streaming TV, Streaming Movies, Streaming Music, Unlimited Data, Contract, Paperless Billing, Payment Method, Monthly Charge, Total Charges, Total Refunds, Total Extra Data Charges, Total Long Distance Charges, Total Revenue, Customer Status, Churn Category, Churn Reason]
Index: []

[0 rows x 38 columns]

<h2> Now to indentify high valued customers

<h3>The goal of most companies is to grow and also generate more income, so it is very likely that the valued customer will be customers that generate more revenue in any way, so only customers with high total revenue and high number of referral will be analysed in this section

In [70]:
#To filter customers that are churned because they are obviously not high valued customers.
unchurned_customers= customer_churn[customer_churn['Customer Status'] != 'Churned']
unchurned_customers.head(2)

Customer ID  Gender  Age Married  Number of Dependents          City  \
0  0002-ORFBO  Female   37     Yes                     0  Frazier Park   
1  0003-MKNFE    Male   46      No                     0      Glendale   

   Zip Code   Latitude   Longitude  Number of Referrals  ...  Payment Method  \
0     93225  34.827662 -118.999073                    2  ...     Credit Card   
1     91206  34.162515 -118.203869                    0  ...     Credit Card   

  Monthly Charge Total Charges  Total Refunds Total Extra Data Charges  \
0           65.6         593.3           0.00                        0   
1           -4.0         542.4          38.33                       10   

  Total Long Distance Charges Total Revenue  Customer Status Churn Category  \
0                      381.51        974.81           Stayed            NaN   
1                       96.21        610.28           Stayed            NaN   

  Churn Reason  
0          NaN  
1          NaN  

[2 rows x 38 columns]

In [71]:
#Number of customers that has generated more than 6000 revenue and has more than 9 referrals
ref= unchurned_customers[unchurned_customers['Number of Referrals']> 9]
rev=ref[ref['Total Revenue']>6000]
rev.sort_values(by ='Total Revenue', ascending=False)
rev10=rev.head(10)
rev10

Customer ID  Gender  Age Married  Number of Dependents            City  \
26   0036-IHMOT  Female   37     Yes                     3         Parlier   
59   0103-CSITQ  Female   20     Yes                     0         Modesto   
145  0238-WHBIQ    Male   25     Yes                     1          Folsom   
236  0363-SVHYR    Male   28     Yes                     3       Paramount   
387  0572-ZJKLT  Female   32     Yes                     1         Chester   
388  0575-CUQOV    Male   76     Yes                     0          Hilmar   
733  1084-MNSMJ  Female   63     Yes                     0       El Dorado   
911  1325-USMEC    Male   58     Yes                     0     Pearblossom   
929  1347-KTTTA    Male   22     Yes                     0  Canyon Country   
938  1357-BIJKI    Male   46     Yes                     0   Mission Viejo   

     Zip Code   Latitude   Longitude  Number of Referrals  ...  \
26      93648  36.622237 -119.521126                   10  ...   
59      95357  37.670526 -120.877572                   10  ...   
145     95630  38.672638 -121.147403                   10  ...   
236     90723  33.897122 -118.164432                   10  ...   
387     96020  40.243494 -121.154733                   10  ...   
388     95324  37.394536 -120.890747                   10  ...   
733     95623  38.631530 -120.842609                   10  ...   
911     93553  34.445239 -117.894868                   10  ...   
929     91351  34.422519 -118.420717                   10  ...   
938     92691  33.611945 -117.665867                   10  ...   

      Payment Method Monthly Charge Total Charges  Total Refunds  \
26   Bank Withdrawal         103.70       5656.75           0.00   
59   Bank Withdrawal         109.40       6252.70           0.00   
145      Credit Card          89.70       6339.30           0.00   
236  Bank Withdrawal          86.85       6263.80           0.00   
387      Credit Card          99.65       4630.20           9.35   
388  Bank Withdrawal          97.95       5867.00           0.00   
733      Credit Card          85.50       4421.95           0.00   
911      Credit Card          99.35       6944.50           0.00   
929      Credit Card         102.45       6654.10           0.00   
938  Bank Withdrawal          98.25       4858.70           3.55   

    Total Extra Data Charges Total Long Distance Charges Total Revenue  \
26                        20                     1927.20       7603.95   
59                         0                      456.57       6709.27   
145                        0                     2430.00       8769.30   
236                        0                      717.81       6981.61   
387                        0                     2265.96       6886.81   
388                        0                     1023.00       6890.00   
733                        0                     1730.43       6152.38   
911                        0                     3360.00      10304.50   
929                        0                     2591.36       9245.46   
938                        0                     1914.50       6769.65   

     Customer Status Churn Category Churn Reason  
26            Stayed            NaN          NaN  
59            Stayed            NaN          NaN  
145           Stayed            NaN          NaN  
236           Stayed            NaN          NaN  
387           Stayed            NaN          NaN  
388           Stayed            NaN          NaN  
733           Stayed            NaN          NaN  
911           Stayed            NaN          NaN  
929           Stayed            NaN          NaN  
938           Stayed            NaN          NaN  

[10 rows x 38 columns]

In [72]:
#Let`s visualize the table above
px.data.gapminder()
for templates in ['plotly_dark']:
 highest_no_rev_fig=px.bar(rev10, x='Customer ID', y='Total Revenue',color_discrete_sequence=px.colors.sequential.RdBu,
  title=' Top 10 customers with highest number of referrals and total revenue', template=templates)
highest_no_rev_fig.show()

In [73]:
#Let`s find out if marriage has any significant effect on the number of unchurned customers
top=unchurned_customers.sort_values(by= 'Total Revenue', ascending=False)
px.data.gapminder()
for templates in ['plotly_dark']:
 marital_fig=px.pie(top,values='Total Revenue', names='Married', hole=.4,color_discrete_sequence=px.colors.sequential.RdBu,
  title= 'Percentage of the marital status of the that is not churned', template=templates)
marital_fig.show()

This shows married people should be definitely valued...but, should they be highly valued?

In [74]:
#Number of married customers that has generated more than 6000 revenue and has more than 9 referrals
mar= rev['Married'].value_counts()
mar

Yes    64
Name: Married, dtype: int64

All customers that generates high revenue(>6000) and has top referrals are all married. This means married people are clearly high valued customers

<h4> Now lets look at the location and know if it has any significance</h4>
<p>lets see</p>

In [75]:
#Top cities that was not churned
print('These are the top 5 cities that was not churned') 
bubble=unchurned_customers['City'].value_counts().head(10).sort_values()
bubble



These are the top 5 cities that was not churned


Escondido         35
Bakersfield       37
Oakland           39
Long Beach        45
Fresno            48
San Francisco     73
Sacramento        82
San Jose          83
San Diego        100
Los Angeles      215
Name: City, dtype: int64

In [76]:
px.data.gapminder()
for templates in ['plotly_dark']:
 top_city_fig=px.bar(bubble,color_discrete_sequence=px.colors.sequential.RdBu,
title= 'Top 10 cities with high number of customers that was not churned',template=templates,
labels={'index':'Cities', 'value':'Count of customers'},
orientation='h' )
top_city_fig.show()


In [77]:
#Let`s select only the rows with the top cities 
lst=['Los Angeles', 'San Diego', 'San Jose', 'Sacramento', 'San Francisco']
top_5_cities=unchurned_customers[unchurned_customers['City'].isin(lst)]
top_5_cities.sort_values(by='Total Revenue', ascending=False).head(5)

Customer ID  Gender  Age Married  Number of Dependents           City  \
5879  8263-QMNTJ    Male   46     Yes                     0  San Francisco   
3879  5451-YHYPW  Female   75     Yes                     0  San Francisco   
567   0835-JKADZ  Female   29      No                     0  San Francisco   
32    0052-DCKON    Male   28     Yes                     0    Los Angeles   
1029  1488-PBLJN  Female   63     Yes                     1      San Diego   

      Zip Code   Latitude   Longitude  Number of Referrals  ...  \
5879     94104  37.791222 -122.402241                    2  ...   
3879     94129  37.797526 -122.464531                    2  ...   
567      94107  37.768881 -122.395521                    0  ...   
32       90063  34.044271 -118.185237                    9  ...   
1029     92124  32.827238 -117.089287                    1  ...   

       Payment Method Monthly Charge Total Charges  Total Refunds  \
5879  Bank Withdrawal         115.55       8425.30            0.0   
3879      Credit Card         115.75       8443.70            0.0   
567   Bank Withdrawal         111.25       7984.15            0.0   
32    Bank Withdrawal          -2.00       7942.15            0.0   
1029  Bank Withdrawal         116.85       8477.70            0.0   

     Total Extra Data Charges Total Long Distance Charges Total Revenue  \
5879                        0                     3443.04      11868.34   
3879                      120                     3232.08      11795.78   
567                         0                     2976.32      10960.47   
32                          0                     2888.82      10830.97   
1029                        0                     2291.76      10769.46   

      Customer Status Churn Category Churn Reason  
5879           Stayed            NaN          NaN  
3879           Stayed            NaN          NaN  
567            Stayed            NaN          NaN  
32             Stayed            NaN          NaN  
1029           Stayed            NaN          NaN  

[5 rows x 38 columns]

In [78]:
#TCWHRHR stands for Top Cities With High Referrals & High Revenue
TCWHRHR =top_5_cities[top_5_cities['Number of Referrals']>9].sort_values(by='Total Revenue', ascending=False)
main=TCWHRHR.head(10)
main


Customer ID  Gender  Age Married  Number of Dependents           City  \
3555  5038-ETMLM  Female   35     Yes                     0     Sacramento   
6135  8690-ZVLCL  Female   49     Yes                     1    Los Angeles   
6158  8722-PRFDV  Female   21     Yes                     3    Los Angeles   
6375  9031-ZVQPT    Male   21     Yes                     0  San Francisco   
2327  3327-YBAKM  Female   31     Yes                     0      San Diego   
2198  3148-AOIQT  Female   23     Yes                     0     Sacramento   
5903  8313-AFGBW    Male   55     Yes                     0    Los Angeles   
60    0104-PPXDV    Male   61     Yes                     0      San Diego   
2466  3528-HFRIQ    Male   73     Yes                     0    Los Angeles   
3239  4636-JGAAI    Male   28     Yes                     0       San Jose   

      Zip Code   Latitude   Longitude  Number of Referrals  ...  \
3555     95823  38.475465 -121.443625                   10  ...   
6135     90038  34.088017 -118.327168                   10  ...   
6158     90042  34.115720 -118.192754                   10  ...   
6375     94109  37.794487 -122.422270                   10  ...   
2327     92131  32.893250 -117.087091                   10  ...   
2198     95837  38.691607 -121.602284                   10  ...   
5903     90008  34.008293 -118.346766                   10  ...   
60       92113  32.697098 -117.116587                   10  ...   
2466     90068  34.137411 -118.328915                   10  ...   
3239     95120  37.186141 -121.843554                   10  ...   

       Payment Method Monthly Charge Total Charges  Total Refunds  \
3555  Bank Withdrawal         113.65       8182.75           0.00   
6135      Credit Card          88.00       6161.90           0.00   
6158      Credit Card          77.55       5574.35           0.00   
6375  Bank Withdrawal         108.20       7840.60           0.00   
2327      Credit Card          96.90       6314.35          13.37   
2198      Credit Card          24.95       1718.35           0.00   
5903  Bank Withdrawal          73.60       3522.65           0.00   
60        Credit Card          50.30       2878.55          10.23   
2466  Bank Withdrawal          52.30       3765.05           0.00   
3239      Credit Card          88.85       3000.25           0.00   

     Total Extra Data Charges Total Long Distance Charges Total Revenue  \
3555                        0                     2088.00      10270.75   
6135                       40                     2958.68       9160.58   
6158                        0                     3461.96       9036.31   
6375                        0                     1021.68       8862.28   
2327                        0                     1230.08       7531.06   
2198                        0                     3113.28       4831.63   
5903                        0                      664.58       4187.23   
60                          0                     1065.46       3933.78   
2466                       40                        0.00       3805.05   
3239                        0                      474.98       3475.23   

      Customer Status Churn Category Churn Reason  
3555           Stayed            NaN          NaN  
6135           Stayed            NaN          NaN  
6158           Stayed            NaN          NaN  
6375           Stayed            NaN          NaN  
2327           Stayed            NaN          NaN  
2198           Stayed            NaN          NaN  
5903           Stayed            NaN          NaN  
60             Stayed            NaN          NaN  
2466           Stayed            NaN          NaN  
3239           Stayed            NaN          NaN  

[10 rows x 38 columns]

In [92]:
#Let`s see if age has any effect

px.data.gapminder()
for templates in ['plotly_dark']:
 age_fig= px.histogram(main, x='Age', y='Total Revenue', color_discrete_sequence=px.colors.sequential.RdBu,
 title='Total age of people with high revenue and high referrals by age',  template=templates)
 age_fig.show()

This is the age of people with high revenue and high referrals</p>
This shows that younger people generated more revenue

In [80]:
main1=main[main['Tenure in Months']>60].sort_values(by= 'Age', ascending=False)
main1

Customer ID  Gender  Age Married  Number of Dependents           City  \
2466  3528-HFRIQ    Male   73     Yes                     0    Los Angeles   
6135  8690-ZVLCL  Female   49     Yes                     1    Los Angeles   
3555  5038-ETMLM  Female   35     Yes                     0     Sacramento   
2327  3327-YBAKM  Female   31     Yes                     0      San Diego   
2198  3148-AOIQT  Female   23     Yes                     0     Sacramento   
6158  8722-PRFDV  Female   21     Yes                     3    Los Angeles   
6375  9031-ZVQPT    Male   21     Yes                     0  San Francisco   

      Zip Code   Latitude   Longitude  Number of Referrals  ...  \
2466     90068  34.137411 -118.328915                   10  ...   
6135     90038  34.088017 -118.327168                   10  ...   
3555     95823  38.475465 -121.443625                   10  ...   
2327     92131  32.893250 -117.087091                   10  ...   
2198     95837  38.691607 -121.602284                   10  ...   
6158     90042  34.115720 -118.192754                   10  ...   
6375     94109  37.794487 -122.422270                   10  ...   

       Payment Method Monthly Charge Total Charges  Total Refunds  \
2466  Bank Withdrawal          52.30       3765.05           0.00   
6135      Credit Card          88.00       6161.90           0.00   
3555  Bank Withdrawal         113.65       8182.75           0.00   
2327      Credit Card          96.90       6314.35          13.37   
2198      Credit Card          24.95       1718.35           0.00   
6158      Credit Card          77.55       5574.35           0.00   
6375  Bank Withdrawal         108.20       7840.60           0.00   

     Total Extra Data Charges Total Long Distance Charges Total Revenue  \
2466                       40                        0.00       3805.05   
6135                       40                     2958.68       9160.58   
3555                        0                     2088.00      10270.75   
2327                        0                     1230.08       7531.06   
2198                        0                     3113.28       4831.63   
6158                        0                     3461.96       9036.31   
6375                        0                     1021.68       8862.28   

      Customer Status Churn Category Churn Reason  
2466           Stayed            NaN          NaN  
6135           Stayed            NaN          NaN  
3555           Stayed            NaN          NaN  
2327           Stayed            NaN          NaN  
2198           Stayed            NaN          NaN  
6158           Stayed            NaN          NaN  
6375           Stayed            NaN          NaN  

[7 rows x 38 columns]

This shows that people that have stayed for close to 2 months have generated more revenue

In [81]:
#Let`s look at Tenure and contract period fo the customers 
main3= main1[[ 'Customer ID','Tenure in Months', 'Contract', 'Total Revenue']].sort_values(by= 'Contract', ascending=False)
main3



Customer ID  Tenure in Months        Contract  Total Revenue
6135  8690-ZVLCL                68        Two Year        9160.58
3555  5038-ETMLM                72        Two Year       10270.75
2198  3148-AOIQT                69        Two Year        4831.63
6158  8722-PRFDV                71        Two Year        9036.31
6375  9031-ZVQPT                72        Two Year        8862.28
2327  3327-YBAKM                64        One Year        7531.06
2466  3528-HFRIQ                71  Month-to-Month        3805.05

In [82]:
px.data.gapminder()
for templates in ['plotly_dark']:
 contract_period_fig=px.bar(main3, x='Customer ID', y='Total Revenue', color= 'Contract',color_discrete_sequence=px.colors.sequential.RdBu, 
title= 'Contract period of customers that have stayed for more than 2 months(60>days)', template=templates )
contract_period_fig.show()

5038-ETMLM, 8690-ZVLCL, 8722-PRFDV, 9031-ZVQPT, 3327-YBAKM, 3148-AOIQT and 3528-HFRIQ are likely the high valued customers because they have referred more people, generated high revenue and have stayed for a long time with the company

In [83]:
import pandas as pd
from jupyter_dash import JupyterDash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

In [84]:
import plotly.io as pio
pio.templates

Templates configuration
-----------------------
    Default template: 'plotly'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none']

In [96]:
# Import required library
import dash
from jupyter_dash import JupyterDash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output
import dash_bootstrap_components as dbc
import plotly.io as pio 




# Create a dash application
app = JupyterDash(__name__)

colors={
    'background':'#121212'
}

# Build dash app layout
app.layout = html.Div(style={'backgroundColor': colors['background']},children=[html.H1('Identifying high valued customers Statistics',
                                        style={'textAlign': 'center', 'color': '#503D36',
                                               'font-size': 30}),
                                html.Div(["Input Year: ", dcc.Input(id='input-year', value='2022',
                                                                    type='number',
                                                                    style={'height': '35px', 'font-size': 30}), ],
                                         style={'font-size': 30, 'color':'white'}),
                                html.Br(),
                                html.Br(),
                                
                                # Segment 1
                                html.Div([
                                    html.Div(dcc.Graph(id='Categories-plot')),
                                    html.Div(dcc.Graph(id='Reason-plot'))
                                ], style={'display': 'flex'}),
                                # Segment 2
                                html.Div([
                                    html.Div(dcc.Graph(id='Customers-plot')),
                                    html.Div(dcc.Graph(id='Marital-plot'))
                                ], style={'display': 'flex'}),
                                # Segment 3
                                html.Div([
                                    html.Div(dcc.Graph(id='Age-plot')),
                                    html.Div(dcc.Graph(id='Period-plot'))
                                ], style={'display': 'flex'}),
                                # Segment 4
                                html.Div([
                                html.Div(dcc.Graph(id='offer-plot')),
                                html.Div(dcc.Graph(id='city-plot'))
                                ], style={'display': 'flex'}),

                                html.Div([dcc.Markdown('''

                                    ### Insights and recommendations
                                    
                                    
                                    * Large number of customers switched because they got better offer and most of them got 'Offer E' so review and improve 'Offer E'.
                                    * Married people should be highly valued because they have higher percentage of people that stayed and it will be good to note that all the customers with high referrals and high revenue are all married
                                    * Customers that have been in the company for more than 60 days with 2 years contract are also high valued because they generate more revenue.
                                    * Younger people (20-40) generated more revenue and had higher referrals so could be considered as high valued customers 
                                    * In conclusion, **5038-ETMLM, 8690-ZVLCL, 8722-PRFDV, 9031-ZVQPT, 3327-YBAKM, 3148-AOIQT and 3528-HFRIQ** are likely the high valued customers because 
                                    they have referred more people, generated high revenue and have stayed for a long time with the company.
                                ''')

                                ], style={'color':'#F1F1F1'})

                                ])

""" Compute_info function description

This function takes in Telecommunication churn data and selected year as an input and performs computation for creating charts and plots.

Arguments:
    Telecommunication churn data: Input customers data.
    entered_year: Input year for which computation needs to be performed.

Returns:
    Computed average dataframes for charts of the above analysis, insights and recommendations

"""


def compute_info(customer_churn):
 
    # Compute the above analysis
 churn_cat = easy1
 churn_res = comp1
 city_val=bubble
 high_val = rev10
 marital_stats = top
 rev_age = main
 off_type=offer
 cus_per=main3
 return churn_cat, churn_res, high_val, marital_stats, rev_age, off_type, cus_per, city_val


"""Callback Function

Function that returns figures using the provided input year.

Arguments:

    entered_year: Input year provided by the user.

Returns:

    List of figures computed using the provided helper function `compute_info`.
"""


# Callback decorator
@app.callback([
    Output('Categories-plot','figure'),
    Output('Reason-plot','figure'),
    Output('Customers-plot','figure'),
    Output('Marital-plot','figure'),
    Output('Age-plot','figure'),
    Output('offer-plot', 'figure'),
    Output('Period-plot','figure'),
    Output('city-plot','figure'),
],
    Input(component_id='input-year', component_property='value'))
# Computation to callback function and return graph
def get_graph(customer_churn):
    # Compute required information for creating graph from the data
    churn_cat, churn_res, high_val, marital_stats, rev_age, city_val, cus_per, off_type= compute_info(customer_churn)

    # Bar plot for category of churned customers
    cat_fig=category_fig
    # Horizontal bar plot for reasons why people leave
    res_fig=reason_for_leaving_fig
    # Bar plot of people with high referrals and high revenue
    cusID_fig=highest_no_rev_fig
    # Doughnut chart of marital status
    mar_fig=marital_fig
    # Horizontal plot of the top cities with higher number of customers
    city_fig=top_city_fig
    # Histogram plot of the age of customers with highest number of revenue and high referrals 
    revage_fig=age_fig
    #Scatter plot of offers given to the churned customers
    offer_fig=offer_no_fig
    #Bar plot of customers tenure
    ctc_fig=contract_period_fig

    return[cat_fig, res_fig,offer_fig, cusID_fig, mar_fig,revage_fig,city_fig, ctc_fig]


# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8099)



Dash app running on http://127.0.0.1:8099/
